version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  auth:
    build:
      context: ./SCD_Q1_Auth
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  blogs:
    build:
      context: ./SCD_Q1_Blogs
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - app-network
    depends_on:
      - auth
      - mongodb

  comments:
    build:
      context: ./SCD_Q1_Comments
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    networks:
      - app-network
    depends_on:
      - auth
      - blogs
      - mongodb

  profile:
    build:
      context: ./SCD_Q1_Profile
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    networks:
      - app-network
    depends_on:
      - auth
      - mongodb

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: